export LANG="en_IE.UTF-8"
export LC_ALL=$LANG
export LC_COLLATE=$LANG
export LC_CTYPE=$LANG
export LC_MESSAGES=$LANG
export LC_MONETARY=$LANG
export LC_NUMERIC=$LANG
export LC_TIME=$LANG

export XDG_CACHE_HOME="$HOME/.cache"
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.data"
export XDG_STATE_HOME="$HOME/.state"

export XDG_MUSIC_DIR="$HOME/media/audio"

export PATH="$PATH:$HOME/.local/bin"
export PATH="$PATH:$HOME/.cargo/bin"
export PATH="$PATH:$HOME/.config/emacs/bin"
export PATH="$PATH:$HOME/Library/Application Support/JetBrains/Toolbox/scripts"

export HOMEBREW_BUNDLE_FILE="$HOME/sys/Brewfile"

export EDITOR="micro"

export TERM="xterm-256color"

# Colorize man pages using `bat`.
export MANPAGER="sh -c 'col -bx | bat -l man -p'"

# Default is "~/Library/Application Support/eza".
# Setting this doesn't override it.
# TODO: Figure out why.
export EZA_CONFIG_DIR="$HOME/.config/eza"

. "$HOME/.cargo/env"
